service: product-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

# DB Variables
  environment:
    PG_HOST: '${env:PG_HOST}'
    PG_PORT: '${env:PG_PORT}'
    PG_DATABASE: '${env:PG_DATABASE}'
    PG_USERNAME: '${env:PG_USERNAME}'
    PG_PASSWORD: '${env:PG_PASSWORD}'


functions:
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          path: products
          method: get
          cors: true
  
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request: 
            parameters: 
              paths: 
                productId: true
  
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true